### ISSUE TITLE
ThreadedNmapScan - RuntimeError: Unfulfilled dependency at run time: ParseMasscanOutput

### ISSUE THREAD

**Issue by JayPowerUser** [epi052/recon-pipeline#35]
First of all great tool and concept. I was following your blog and you have some great content.

When I try and run the ThreadedNmapScan I keep getting the following error. Regardless of system tried on Kali and Ubuntu 18.04. For some reason ThreadedNmapScan keeps failing. Even after following your blog and going in order. 
Any thoughts? 
```bash
RROR: [pid 13755] Worker Worker(salt=888760442, workers=1, host=jay-Z68MX-UD2H-B3, username=hack0r, pid=13755) failed    ThreadedNmapScan(target_file=/tmp/tmp6om43n4f, db_location=/home/hack0r/.local/recon-pipeline/databases/ffdff, results_dir=recon-results, exempt_list=, rate=1000, interface=enp4s0, top_ports=1000, ports=, threads=1)
Traceback (most recent call last):
  File "/home/hack0r/.local/share/virtualenvs/recon-pipeline-5UTm9lmr/lib/python3.7/site-packages/luigi/worker.py", line 184, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: ParseMasscanOutput__home_hack0r__lo__enp4s0_f37f7cfb3e
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   ThreadedNmapScan__home_hack0r__lo__enp4s0_bb8aab3923   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 1 pending tasks possibly being run by other workers
DEBUG: There are 1 pending tasks unique to this worker
DEBUG: There are 1 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=888760442, workers=1, host=jay-Z68MX-UD2H-B3, username=hack0r, pid=13755) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 1 complete ones were encountered:
    - 1 MasscanScan(...)
* 1 ran successfully:
    - 1 ParseMasscanOutput(...)
* 1 failed:
    - 1 ThreadedNmapScan(...)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

```

**Comment by epi052** [comment]
Good morning, 
Thanks for checking out the blog!  

It looks as though your nmap scan is failing to find results from masscan.  Check the discussion on #30.  

Luigi determines whether or not a node in the pipeline is complete based on the results directory and the database (depending on which node we're talking about).  It looks like your masscan failed to return any meaningful results.  

What are the results of `view ports`?  I suspect there's nothing.  

Try specifying a different `results-dir`.  This should start the scan again from the start.  Assuming you get results from masscan for the new scan, nmap should then proceed as normal.  

Let me know how it turns out!

**Comment by JayPowerUser** [comment]
That was right thanks for the quick response! I was just running it on my local network and wasn't getting any open ports. Firewall was blocking the requests.
