### ISSUE TITLE
QoL Improvement: scan tab completion for installed

### ISSUE THREAD

**Issue by GreaterGoodest** [epi052/recon-pipeline#65]
When tab completing scan commands, all possible commands are shown, not just installed commands.

Tab completion should only show available installed commands.

**Comment by epi052** [comment]
Since we're moving away from pickling tool data, we really just need to decide where the state for tool status (installed vs. not) should live.  Once that's done, a pretty simple alteration to the argparse parser for the scan command would take care of this.  Overall, a pretty simple change, once a decision is made.
